CloudStore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CloudStore.Models
{
    public class Cart
    {
        public int Id { get; set; }
        public string UserId { get; set; }        
        public ApplicationUser User { get; set; }
        public ICollection<Order> Orders { get; set; }
        public virtual ICollection<Line> Lines { get; set; }
        public Cart()
        {
            Orders = new List<Order>();
            Lines = new List<Line>();
        }        
    }    
}

CloudStore/Controllers/CartController.cs
using CloudStore.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Threading.Tasks;

namespace CloudStore.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        StoreContext db = new StoreContext();
        string SPNotAviable = "Нет в наличии";
        string SOAccepted = "Принят";
        public Cart GetCart()
        {
            string user = User.Identity.GetUserId();
            var cart = db.Carts.FirstOrDefault(c => String.Equals(c.UserId, user));       
            return cart;
        }
        public List<Line> GetLines()
        {
            int cartid = GetCart().Id;
            var list = db.Lines.Include(p => p.Product).Where(c => c.CartId == cartid).ToList();
            return list;
        }
        public RedirectToRouteResult AddToCart(int Id, string returnUrl, int quantity)
        {
            string strerror = null;            
            Product product = db.Products.FirstOrDefault(p => p.Id == Id);
            if (product != null && product.Stock >= quantity)
            {
                var sline = db.Lines.Where(p => p.ProductId == product.Id).FirstOrDefault();
                if (sline == null)
                {
                    Line line = new Line
                    {
                        ProductId = product.Id,
                        Quantity = quantity
                    };
                    GetCart().Lines.Add(line);
                }
                else
                {
                    sline.Quantity += quantity;
                }
                product.Stock -= quantity;
                if (product.Stock < 1)
                {
                    var stp = db.StatusProducts.FirstOrDefault(s => String.Equals(s.StatusProductName, SPNotAviable));
                    product.StatusProductId = stp.Id;
                }
                db.Entry(product).State = EntityState.Modified;
                //GetCart().Products.Add(product);                
                db.SaveChanges();
            }
            else
            {
                ModelState.AddModelError("Quantity", "Для добавления недостаточно количества на складе. Доступно: " + product.Stock);
                strerror = String.Format("Для добавления недостаточно количества на складе. Доступно: {0}", product.Stock);
            }
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", new { returnUrl });
            }
            return RedirectToAction("DetailsItem", "Catalog", new { Id = Id, Err = strerror });
        }
        public RedirectToRouteResult RemoveFromCart(int Id, string returnUrl)
        {
            Line line = db.Lines.First(p => p.Id == Id);
            if (line != null)
            {
                Product product = db.Products.FirstOrDefault(p => p.Id == line.ProductId);
                product.Stock += line.Quantity;
                db.Lines.Remove(line);                
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectResult AddProductRequest(int Id, string returnUrl)
        {
            string userid = User.Identity.GetUserId();
            string prname = db.Products.Find(Id).ProductName;
            ProductRequest pr = new ProductRequest { ProductId = Id, UserId = userid };            
            db.ProductRequests.Add(pr);
            db.SaveChanges();
            TempData["message"] = string.Format("Заявка на {0} успешно принята!", prname);
            return Redirect(returnUrl);
        }
        // GET: Cart
        public ActionResult Index(string returnUrl)
        {            
            return View(new CartIndexViewModel
            {                
                Cart = GetCart(),
                Lines = GetLines(),
                ReturnUrl = returnUrl
            });
        }
        public PartialViewResult Summary()
        {
            return PartialView(GetCart());
        }
        public ActionResult Checkout()
        {
            SelectList paymentmethod = new SelectList(db.PaymentMethods, "Id", "PaymentMethodName");
            SelectList typedelivery = new SelectList(db.TypeDeliveries, "Id", "TypeDeliveryName");           
            decimal value = GetLines().Sum(s => s.Product.Cost * s.Quantity);
            ViewBag.Value = value;
            ViewBag.PaymentMethod = paymentmethod;
            ViewBag.TypeDelivery = typedelivery;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Checkout(Order order)
        {
            string orderdescription = null;
            int cartid = GetCart().Id;
            decimal value = GetLines().Sum(s => s.Product.Cost * s.Quantity);
            string userid = User.Identity.GetUserId();
            foreach (var cart in GetLines())
            {
                orderdescription += String.Format("{0} Цена {1} руб Количество {2} штук. {3} ", cart.Product.ProductName, cart.Product.Cost, cart.Quantity, String.Empty);
                for (int i = 0; i < cart.Quantity; i++)
                {
                    SaleStat stat = new SaleStat
                    {
                        ProductId = cart.Product.Id,
                        UserId = userid,
                        Date = DateTime.Now
                    };
                    db.SaleStats.Add(stat);
                }                
            }
            order.Date = DateTime.Now;
            order.CartId = cartid;
            order.Description = orderdescription;
            order.Value = value;
            var storder = db.StatusOrders.FirstOrDefault(s => String.Equals(s.StatusOrderName, SOAccepted));
            order.StatusOrderId = storder.Id;
            if (GetCart().Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.Lines.RemoveRange(GetLines());
                await db.SaveChangesAsync();
                return View("Completed");
            }
            else
            {
                return View(GetCart());
            }
        }

    }
}

CloudStore/Views/Cart/Checkout.cshtml
@using CloudStore.Models
@model Order

@{
    ViewBag.Title = "Оформление заказа";
}

<h2>Оформление заказа</h2>

<hr />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.Label("Тип доставки", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeDeliveryId", ViewBag.TypeDelivery as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeDeliveryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Город", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Улица", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Дом", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.House, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.House, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Корпус", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Housing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Housing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Квартира", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Flat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Flat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Телефон", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.Label("Способ оплаты", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PaymentMethodId", ViewBag.PaymentMethod as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PaymentMethodId, "", new { @class = "text-danger" })
            </div>
        </div>   
        
        <div class="form-group">
            @Html.Label("Итого", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @ViewBag.Value руб
            </div>
        </div> 

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Оформить заказ" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CloudStore/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ";
}

<h2>Спасибо!</h2>

<p>Ваш заказ успешно принят.</p>
<p>Подробности и статус заказа вы можете посмотреть в <a href="@Url.Action("Index", "Manage")">профиле</a>.</p>

<a class="btn btn-default" href="@Url.Action("Index", "Home")">Назад</a>

CloudStore/Views/Cart/Index.cshtml
@model CloudStore.Models.CartIndexViewModel

@{
    ViewBag.Title = "Корзина";
}

<h2>Корзина</h2>

@if (Model.Cart.Lines.Count == 0)
{
    <h4>Ваша корзина в данный момент пуста, для оформления заказа добавьте товар в корзину</h4>

    if (Model.ReturnUrl == null)
    {
        <a class="btn btn-default" href="@Url.Action("Index", "Home")">Назад</a>
    }
    else
    {
        <a class="btn btn-default" href="@Model.ReturnUrl">Назад</a>
    }
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Количество</th>
                <th>Товар</th>
                <th class="text-right">Цена</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Lines)
            {
                <tr>
                    <td class="text-left">
                        <img class="img-thumbnail" width="75" height="89" src="data:image/jpeg;base64, @Convert.ToBase64String(item.Product.Photo)" />
                    </td>
                    <td class="text-left">@item.Quantity</td>
                    <td class="text-left">@item.Product.ProductName</td>
                    <td class="text-right">@item.Product.Cost.ToString("# руб")</td>
                    <td>
                        @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                            @Html.Hidden("Id", item.Id)
                            @Html.HiddenFor(x => x.ReturnUrl)
                            <input type="submit" class="btn btn-danger" value="Удалить" />
                        }
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-left">Итого:</td>
                <td colspan="2" class="text-right">
                    @Model.Lines.Sum(s => s.Product.Cost * s.Quantity).ToString("# руб")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-center">
        @if (Model.ReturnUrl == null)
        {
            <a class="btn btn-default" href="@Url.Action("Index", "Home")">Назад</a>
        }
        else
        {
            <a class="btn btn-default" href="@Model.ReturnUrl">Назад</a>
        }
        @Html.ActionLink("Оформить заказ", "Checkout", null, new { @class = "btn btn-default" })
    </div>
}

CloudStore/Views/Cart/Summary.cshtml
@model CloudStore.Models.Cart

@Model.Lines.Sum(s => s.Quantity)