CloudStore/Controllers/CatalogController.cs
using CloudStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Microsoft.AspNet.Identity;

namespace CloudStore.Controllers
{
    public class CatalogController : Controller
    {
        StoreContext db = new StoreContext();
        public int pagesize = 5;
        // GET: Items
        public ActionResult Index()
        {
            //var product = from p in db.Products where p.Categories.
            //var productt = db.Products.Include(c => c.Manufacturer).Include(c => c.StatusProduct).Include(c => c.Categories).ToList();
            //var products = productt.Where(c => c.Categories. == id).ToList();
            //var products = db.Products.Include(c => c.Categories.Where(p => p.Id == id)).ToList();
            //return View(products);
            List<Category> categories = db.Categories.ToList();
            return View(categories);
        }
        public ActionResult Items(int id, int? manufacturer, int page = 1)
        {
            var category = db.Categories.Find(id);
            string categoryname = category.CategoryName;
            ViewBag.CategoryName = categoryname;
            ViewBag.mid = manufacturer;
            var product = db.Products
                .Include(c => c.Manufacturer)
                .Include(c => c.StatusProduct)
                .Include(c => c.Categories)
                .Where(c => c.Categories.Any(cc => cc.Id == id));
                //.Where(c => manufacturer == null || c.Manufacturer.Name == manufacturer)
                //.ToList();
            if (manufacturer != null && manufacturer != 0)
            {
                product = product.Where(c => c.ManufacturerId == manufacturer);
            }
            List<Product> products = product.ToList();
            var manufacturers = db.Manufacturers.Where(m => m.Products.Any(p => p.Categories.Any(c => c.Id == id))).ToList();
            manufacturers.Insert(0, new Manufacturer { ManufacturerName = "Все", Id = 0 });
            ProductListViewModel model = new ProductListViewModel
            {
                Products = products.Where(m => manufacturer == null || manufacturer == 0 || m.ManufacturerId == manufacturer).OrderBy(p => p.Id).Skip((page - 1) * pagesize).Take(pagesize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pagesize,
                    TotalItems = manufacturer == 0 || manufacturer == null ? products.Count() : db.Products.Where(c => c.Categories.Any(cc => cc.Id == id)).Where(m => m.ManufacturerId == manufacturer).Count()                    
                },
                Manufacturers = new SelectList(manufacturers, "Id", "ManufacturerName")
                
            };
            return View(model);
        }
        [HttpGet]
        public ActionResult SearchResult(string search)
        {
            ViewBag.SearchResult = search;
            var searchresult = db.Products.Where(p=> p.ProductName.Contains(search)).Include(c => c.Manufacturer).Include(c => c.StatusProduct).Include(c => c.Categories).ToList();
            return View(searchresult);            
        }
        public ActionResult DetailsItem(int id, string err = null)
        {            
            var productt = db.Products.Include(c => c.Manufacturer).Include(c => c.StatusProduct).Include(c => c.Categories).ToList();
            var product = productt.Find(i => i.Id == id);
            ViewBag.Err = err;
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }        
    }
}

CloudStore/Views/Catalog/DetailsItem.cshtml
@model CloudStore.Models.Product

@{
    //ViewBag.Title = Model.Manufacturer.Name + " " + Model.Name;
    ViewBag.Title = "Создание товара";
}

<br />

<div class="row">
    <div class="col-sm-8">
        <div align="center"><img class="thumbnail" src="data:image/jpeg;base64, @Convert.ToBase64String(Model.Photo)" /></div>
        <h3>Описание:</h3>
        <p>@Model.Description</p>        
    </div>
    <div class="col-sm-4">
        <h1>@Model.ProductName</h1>
        <p>Производитель: @Model.Manufacturer.ManufacturerName</p>
        <h2>@Model.Cost.ToString("# руб")</h2>
        <h3>@Model.StatusProduct.StatusProductName</h3>
        @if (Model.StatusProduct.StatusProductName == "Нет в наличии" || Model.StatusProduct.StatusProductName == "Снят с производства")
        {
            <div class="form-group">
                <button class="btn btn-default disabled btn-lg btn-block">Добавить в корзину</button>
                @using (Html.BeginForm("AddProductRequest", "Cart"))
                {
                    <br />                
                    @Html.HiddenFor(x => x.Id)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)                    
                    <input type="submit" class="btn btn-default btn-lg btn-block" value="Оповестить об наличии товара" />
                
                }
            </div>
        }
        else
        {
            using (Html.BeginForm("AddToCart", "Cart"))
            {                                              
                <div class="form-group">
                    @Html.HiddenFor(x => x.Id)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)                    
                    <label for="inputquantity">Количество</label>
                    <input class="form-control" type="number" min="1" value="1" name="quantity" id="inputquantity" />
                    @if (ViewBag.Err != null)
                    {
                        <div class="text-danger">@ViewBag.Err</div>
                    }
                    <br />
                    <input type="submit" class="btn btn-default btn-lg btn-block" value="Добавить в корзину" />
                </div>
            }
        }
    </div>
</div>

CloudStore/Views/Catalog/Index.cshtml
@using CloudStore.Models
@model IEnumerable<Category>

@{
    ViewBag.Title = "Категории";
}

<h2>Категории</h2>

<br />

<div class="pull-right">
    <form method="get" action="@Url.Action("SearchResult", "Catalog")">        
        <input type="text" name="search" id="search" />
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span>Поиск</button>
    </form>
</div>

<ul class="menu">

    @foreach (var c in Model.Where(p => p.ParentCategoryId == null))
    {

        <li>            
            @Html.ActionLink(c.CategoryName, "Items", new { id = c.Id }, new { @class = "btn btn-default" })
            @if (Model.Count(p => p.ParentCategoryId == c.Id) > 0)
            {
                @:<ul>
        }

            @RenderMenuItem(Model, c)

            @if (Model.Count(p => p.ParentCategoryId == c.Id) > 0)
            {
                @:</ul>
            }

        </li>
    }
</ul>


@helper RenderMenuItem(IEnumerable<Category> category, Category cat)
{
foreach (var cp in category.Where(p => p.ParentCategoryId == cat.Id))
{


        @:<li>
            @Html.ActionLink(cp.CategoryName, "Items", new { id = cp.Id }, new { @class = "btn btn-default" })

    if (category.Count(p => p.ParentCategoryId == cp.Id) > 0)
    {
            @:<ul>
        }

        @RenderMenuItem(category, cp)
    if (category.Count(p => p.ParentCategoryId == cp.Id) > 0)
    {
            @:</ul>
    }
    else
    {
            @:</li>
    }
}
}

CloudStore/Views/Catalog/Items.cshtml
@using CloudStore.Models
@model ProductListViewModel
@using CloudStore.Infastructure

@{
    ViewBag.Title = ViewBag.CategoryName;
}

<h2>@ViewBag.CategoryName</h2>
<hr />

<div class="row panel">
    <div class="col-md-2">
        <form method="get">
            <div class="form-inline">
                <label class="control-label">Производитель</label>                
                    <p>@Html.DropDownList("manufacturer", Model.Manufacturers as SelectList, htmlAttributes: new { @class = "form-control" })</p>                    
                   <input type="submit" value="Фильтр" class="btn btn-default" />
               
            </div>
        </form>
    </div>
    <div class="col-md-10">
        @foreach (var item in Model.Products)
        {
            <div class="well">
                @if (item.Photo != null)
                {
                    <div class="pull-left" style="margin-right: 10px">
                        <img class="img-thumbnail" width="75" height="89" src="data:image/jpeg;base64, @Convert.ToBase64String(item.Photo)" />
                    </div>
                }
                <h3>
                    <strong>@Html.ActionLink(item.Manufacturer.ManufacturerName + " " +item.ProductName, "DetailsItem", new { id = item.Id })</strong>
                    <span class="pull-right label label-default">@item.Cost.ToString("# руб")</span>
                </h3>
                <span class="lead">@item.Description</span>
                <h4><b>@item.StatusProduct.StatusProductName</b></h4>
            </div>
        }
    </div>
</div>

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("Items", new { page = x, manufacturer = ViewBag.mid }))
</div>

CloudStore/Views/Catalog/SearchResult.cshtml
@model IEnumerable<CloudStore.Models.Product>

@{
    ViewBag.Title = "Результаты поиска";
}

<h2>Результаты поиска: @ViewBag.SearchResult</h2>

<hr />

@foreach (var item in Model)
{
    <div class="well">
        @if (item.Photo != null)
                {
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="89" src="data:image/jpeg;base64, @Convert.ToBase64String(item.Photo)" />
            </div>
        }
        <h3>
            <strong>@Html.ActionLink(item.Manufacturer.ManufacturerName + " " + item.ProductName, "DetailsItem", new { id = item.Id })</strong>
            <span class="pull-right label label-default">@item.Cost.ToString("# руб")</span>
        </h3>
        <span class="lead">@item.Description</span>
        <h4><b>@item.StatusProduct.StatusProductName</b></h4>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>